### ISSUE TITLE
Versioning bug in setuptools backend

### ISSUE THREAD

**Issue by Saransh-cpp** [osl-incubator/scicookie#187]
The [setuptools-pyproject.toml](https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/%7B%7Bcookiecutter.project_slug%7D%7D/build-system/setuptools-pyproject.toml) file is [missing](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata) -

```toml
[tool.setuptools.dynamic]
version = {attr = "my_package.VERSION"}
```

which causes the generated package to have the version `v0.0.0` always, ignoring the version specified by the user.
