### ISSUE TITLE
Implement depends_on properly, a way to have conditionally questions

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#195]
It would be very valuable to have a alternative flow (questions), that will allow us to have specific questions when the user answer a question with a specific answer.

for example, we could have a sphinx_theme question that will show up to the user, just if the user select the sphinx engine

**Comment by xmnlab** [comment]
for example, the base profile base.yaml could look like:

```yaml

use_git:
  message: Configure the local git repository?
  control_flow: True
  help: ""
  type: "confirm"
  default: True

git_username:
  message: Type the GIT username
  help: https://osl-incubator.github.io/scicookie/guide.html#control-version
  type: "text"
  default: zoro_roronoa
  depends_on:
    use_git: True
```

NOTE: this could be changed in the implementation, it is just an initial idea.
