### ISSUE TITLE
Create `.github/dependabot.yaml`

### ISSUE THREAD

**Issue by Saransh-cpp** [osl-incubator/scicookie#207]
It would be nice to automatically update a few dependencies in scicookie using [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) (for instance, see #190).

I'll install dependabot in this repository once someone creates a PR to add the yaml file. The file can look something like this -
```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # group updates in a single PR
    groups:
      actions:
        patterns:
          - "*"
```
