### ISSUE TITLE
template: The CI should execute just for the main branch

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#214]
change the first lines of the main.yaml file in the template (https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/main.yaml#L1-L3)

to this:

```yaml
name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
```
